receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["host.docker.internal:9464"]

processors:
  batch:
  span/webmvc:
    include:
      match_type: strict
      span_names: ["WebMVCTracingFilter.doFilterInternal"]
    name:
      from_attributes: ["http.url"]
  span/http:
    include:
      match_type: strict
      span_names: ["HTTP GET", "HTTP POST"]
    name:
      from_attributes: ["http.method", "http.url"]
      separator: " "

exporters:
  opencensus/skywalking:
    endpoint: host.docker.internal:11800
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8989"
    namespace: default
  logging:
    logLevel: debug
  jaeger:
    endpoint: host.docker.internal:14250
    insecure: true
  zipkin:
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
  zipkin/skywalking:
    endpoint: "http://host.docker.internal:9422/api/v2/spans"
    format: proto
    insecure: true
  otlp/elastic:
    endpoint: host.docker.internal:8200
    insecure: true

service:
  pipelines:
#    metrics:
#      receivers: [otlp, prometheus]
#      processors: [batch]
#      exporters: [prometheus, logging]
#      exporters: [logging, opencensus/skywalking, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch, span/webmvc, span/http]
      exporters: [
          jaeger,
          zipkin,
          zipkin/skywalking,
          otlp/elastic
      ]
#      exporters: [jaeger, zipkin, zipkin/skywalking]
#      exporters: [logging, opencensus/skywalking, zipkin]
