version: "3.9"
services: 
    prometheus:
        image: 'prom/prometheus:v2.28.0'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    
