version: "3.9"
services: 
    splunk:
        image: 'splunk/splunk:latest'
        ports:
            - 8000:8000 # ui
            #- 14250:14250 # http collector (model.proto)
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=pocDistributed.1
#    splunk-otel-collector: # nome servizio da usare all'interno del container

#   docker run -p 8000:8000 -e "SPLUNK_PASSWORD=<password>" -e "SPLUNK_START_ARGS=--accept-license" -it splunk/splunk:latest