version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: es01
    environment:
      - node.name=es01
#      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  apm:
    image: docker.elastic.co/apm/apm-server:7.13.3
    command: --strict.perms=false -environment container
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    ports:
      - 8200:8200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.3
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - ../logs:/logs:ro
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    volumes:
      - ./logstash.docker.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.docker.yml://usr/share/logstash/config/logstash.yml
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge